In [1]:
import pandas as pd

In [2]:
movies = pd.read_csv("data/movies_converted.csv")

In [3]:
movies.head()

,id,title,overview,genre_ids,popularity,release_date,poster_path,vote_average,vote_count,genres
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,"[18, 80]",41.8985,1994-09-23,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,8.709,28228,"Drama,Crime"
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","[18, 80]",34.4570,1972-03-14,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,8.686,21399,"Drama,Crime"
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,"[18, 80]",14.8922,1974-12-20,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,8.570,12927,"Drama,Crime"
3,424,Schindler's List,The true story of how businessman Oskar Schind...,"[18, 36, 10752]",43.5047,1993-12-15,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,8.564,16402,"Drama,History,War"
4,389,12 Angry Men,The defense and the prosecution have rested an...,[18],14.7159,1957-04-10,/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg,8.548,9102,Drama

In [4]:
movies = movies[["id", "title", "overview", "genres"]]

In [5]:
movies.head()

,id,title,overview,genres
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,"Drama,Crime"
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","Drama,Crime"
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,"Drama,Crime"
3,424,Schindler's List,The true story of how businessman Oskar Schind...,"Drama,History,War"
4,389,12 Angry Men,The defense and the prosecution have rested an...,Drama

In [6]:
movies.loc[:, "tags"] = movies["overview"] + ' ' + movies["genres"]

In [7]:
movies

,id,title,overview,genres,tags
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,"Drama,Crime",Imprisoned in the 1940s for the double murder ...
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","Drama,Crime","Spanning the years 1945 to 1955, a chronicle o..."
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,"Drama,Crime",In the continuing saga of the Corleone crime f...
3,424,Schindler's List,The true story of how businessman Oskar Schind...,"Drama,History,War",The true story of how businessman Oskar Schind...
4,389,12 Angry Men,The defense and the prosecution have rested an...,Drama,The defense and the prosecution have rested an...
...,...,...,...,...,...
9987,314,Catwoman,Liquidated after discovering a corporate consp...,"Action,Fantasy,Crime",Liquidated after discovering a corporate consp...
9988,765119,The Bubble,Sneaking out. Hooking up. Melting down. The ca...,Comedy,Sneaking out. Hooking up. Melting down. The ca...
9989,146203,The Last Exorcism Part II,"As Nell Sweetzer tries to build a new life, th...","Horror,Thriller","As Nell Sweetzer tries to build a new life, th..."
9990,87818,Movie 43,A series of interconnected short films are the...,Comedy,A series of interconnected short films are the...
9991,78049,The Scorpion King 3: Battle for Redemption,Since his triumphant rise to power in the orig...,"Action,Adventure,Fantasy,Drama",Since his triumphant rise to power in the orig...

In [8]:
new_data = movies.drop(columns=["overview", "genres"])

In [9]:
new_data

,id,title,tags
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o..."
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...
3,424,Schindler's List,The true story of how businessman Oskar Schind...
4,389,12 Angry Men,The defense and the prosecution have rested an...
...,...,...,...
9987,314,Catwoman,Liquidated after discovering a corporate consp...
9988,765119,The Bubble,Sneaking out. Hooking up. Melting down. The ca...
9989,146203,The Last Exorcism Part II,"As Nell Sweetzer tries to build a new life, th..."
9990,87818,Movie 43,A series of interconnected short films are the...
9991,78049,The Scorpion King 3: Battle for Redemption,Since his triumphant rise to power in the orig...

In [10]:
from sklearn.feature_extraction.text import CountVectorizer

In [48]:
cv = CountVectorizer(stop_words="english")

In [49]:
cv

CountVectorizer(stop_words='english')

In [80]:
vector = cv.fit_transform(new_data["tags"].values.astype("U"))

In [81]:
vector = vector.toarray()

In [82]:
vector.shape

(9992, 27039)

In [83]:
vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(9992, 27039))

In [53]:
from sklearn.metrics.pairwise import cosine_similarity

In [54]:
similarity = cosine_similarity(vector)

In [55]:
similarity

array([[1.        , 0.11627907, 0.10166571, ..., 0.08151391, 0.        ,
        0.03569722],
       [0.11627907, 1.        , 0.48291214, ..., 0.04075696, 0.        ,
        0.01784861],
       [0.10166571, 0.48291214, 1.        , ..., 0.04454354, 0.04303315,
        0.03901372],
       ...,
       [0.08151391, 0.04075696, 0.04454354, ..., 1.        , 0.        ,
        0.06256112],
       [0.        , 0.        , 0.04303315, ..., 0.        , 1.        ,
        0.03021989],
       [0.03569722, 0.01784861, 0.03901372, ..., 0.06256112, 0.03021989,
        1.        ]], shape=(9992, 9992))

In [65]:
similarity.shape

(9992, 9992)

In [98]:
new_data[new_data["title"]=="The Bubble"]

          id       title                                               tags
9988  765119  The Bubble  Sneaking out. Hooking up. Melting down. The ca...

In [67]:
new_data[new_data["title"]=="The Godfather"].index[0]

np.int64(1)

In [90]:
distance = sorted(list(enumerate(similarity[238])), reverse=True, key=lambda vector:vector[1])

In [91]:
new_data.iloc[distance[1][0]]

id                                                  272878
title                                                  Max
tags     A dog that helped soldiers in Afghanistan retu...
Name: 2708, dtype: object

In [92]:
distance

[(238, np.float64(1.0)),
 (2708, np.float64(0.3952847075210474)),
 (1769, np.float64(0.38348249442368526)),
 (4553, np.float64(0.3296902366978935)),
 (277, np.float64(0.3265986323710904)),
 (929, np.float64(0.3265986323710904)),
 (1694, np.float64(0.30779350562554625)),
 (8072, np.float64(0.3069703067574603)),
 (1338, np.float64(0.30000000000000004)),
 (4226, np.float64(0.30000000000000004)),
 (2336, np.float64(0.298142396999972)),
 (3048, np.float64(0.298142396999972)),
 (4119, np.float64(0.298142396999972)),
 (9454, np.float64(0.298142396999972)),
 (4105, np.float64(0.28867513459481287)),
 (656, np.float64(0.2860387767736777)),
 (109, np.float64(0.2839809171235324)),
 (6545, np.float64(0.2760262237369417)),
 (706, np.float64(0.27386127875258315)),
 (2151, np.float64(0.27386127875258315)),
 (3390, np.float64(0.27386127875258315)),
 (6650, np.float64(0.27386127875258315)),
 (7764, np.float64(0.27386127875258315)),
 (1158, np.float64(0.2738612787525831)),
 (7366, np.float64(0.26967994498529685)),
 (5994, np.float64(0.2696799449852968)),
 (2498, np.float64(0.2637521893583148)),
 (2846, np.float64(0.2637521893583148)),
 (2906, np.float64(0.2637521893583148)),
 (4047, np.float64(0.2637521893583148)),
 (7120, np.float64(0.2637521893583148)),
 (809, np.float64(0.2631174057921088)),
 (2596, np.float64(0.2631174057921088)),
 (2610, np.float64(0.2631174057921088)),
 (3035, np.float64(0.2631174057921088)),
 (4559, np.float64(0.2631174057921088)),
 (6759, np.float64(0.2631174057921088)),
 (8800, np.float64(0.2631174057921088)),
 (9040, np.float64(0.2631174057921088)),
 (8182, np.float64(0.2606233456578416)),
 (2761, np.float64(0.25649458802128855)),
 (1438, np.float64(0.25584085962673253)),
 (2126, np.float64(0.253546276418555)),
 (2650, np.float64(0.253546276418555)),
 (9442, np.float64(0.253546276418555)),
 (9461, np.float64(0.253546276418555)),
 (1763, np.float64(0.24806946917841693)),
 (3059, np.float64(0.24806946917841693)),
 (3404, np.float64(0.24806946917841693)),
 (504, np.float64(0.24693239916239743)),
 (1701, np.float64(0.24693239916239743)),
 (27, np.float64(0.2449489742783178)),
 (419, np.float64(0.2449489742783178)),
 (2552, np.float64(0.2449489742783178)),
 (4971, np.float64(0.2449489742783178)),
 (5246, np.float64(0.2449489742783178)),
 (5500, np.float64(0.2449489742783178)),
 (5877, np.float64(0.2449489742783178)),
 (6311, np.float64(0.2449489742783178)),
 (9867, np.float64(0.2449489742783178)),
 (1516, np.float64(0.24397501823713333)),
 (4574, np.float64(0.24397501823713333)),
 (874, np.float64(0.24343224778007386)),
 (1322, np.float64(0.24343224778007386)),
 (116, np.float64(0.24293289905367482)),
 (882, np.float64(0.24293289905367482)),
 (2644, np.float64(0.23904572186687872)),
 (5266, np.float64(0.23904572186687872)),
 (1301, np.float64(0.23717082451262844)),
 (4349, np.float64(0.23717082451262844)),
 (4840, np.float64(0.23717082451262844)),
 (5803, np.float64(0.23717082451262844)),
 (6901, np.float64(0.23717082451262844)),
 (9845, np.float64(0.23717082451262844)),
 (1000, np.float64(0.23570226039551584)),
 (159, np.float64(0.23488808780588138)),
 (838, np.float64(0.2309401076758503)),
 (914, np.float64(0.2309401076758503)),
 (1051, np.float64(0.2309401076758503)),
 (5652, np.float64(0.2309401076758503)),
 (1178, np.float64(0.23063280200722128)),
 (205, np.float64(0.23008949665421113)),
 (533, np.float64(0.23008949665421113)),
 (2795, np.float64(0.23008949665421113)),
 (2879, np.float64(0.23008949665421113)),
 (4035, np.float64(0.23008949665421113)),
 (5084, np.float64(0.23008949665421113)),
 (6382, np.float64(0.23008949665421113)),
 (8237, np.float64(0.23008949665421113)),
 (5154, np.float64(0.22821773229381925)),
 (661, np.float64(0.22718473369882594)),
 (1161, np.float64(0.22718473369882594)),
 (4847, np.float64(0.22718473369882594)),
 (96, np.float64(0.2258769757263128)),
 (668, np.float64(0.22360679774997902)),
 (1431, np.float64(0.22360679774997902)),
 (1664, np.float64(0.22360679774997902)),
 (3730, np.float64(0.22360679774997902)),
 (3756, np.float64(0.22360679774997902)),
 (4598, np.float64(0.22360679774997902)),
 (5598, np.float64(0.22360679774997902)),
 (5988, np.float64(0.22360679774997902)),
 (8328, np.float64(0.22360679774997902)),
 (8880, np.float64(0.22360679774997902)),
 (9901, np.float64(0.22360679774997902)),
 (6417, np.float64(0.22360679774997896)),
 (8225, np.float64(0.22360679774997896)),
 (388, np.float64(0.22019275302527214)),
 (4671, np.float64(0.22019275302527214)),
 (234, np.float64(0.2176428750330035)),
 (461, np.float64(0.2176428750330035)),
 (1713, np.float64(0.2176428750330035)),
 (1888, np.float64(0.2176428750330035)),
 (3955, np.float64(0.2176428750330035)),
 (4752, np.float64(0.2176428750330035)),
 (4832, np.float64(0.2176428750330035)),
 (8532, np.float64(0.2176428750330035)),
 (3545, np.float64(0.2171861213815347)),
 (3558, np.float64(0.2171861213815347)),
 (463, np.float64(0.21693045781865616)),
 (964, np.float64(0.21693045781865616)),
 (1511, np.float64(0.21693045781865616)),
 (3335, np.float64(0.21693045781865616)),
 (8502, np.float64(0.21693045781865616)),
 (8066, np.float64(0.21516574145596762)),
 (1022, np.float64(0.2138089935299395)),
 (4070, np.float64(0.2138089935299395)),
 (2700, np.float64(0.21320071635561044)),
 (5335, np.float64(0.21320071635561044)),
 (123, np.float64(0.21213203435596426)),
 (350, np.float64(0.21213203435596426)),
 (1443, np.float64(0.21213203435596426)),
 (1449, np.float64(0.21213203435596426)),
 (4081, np.float64(0.21213203435596426)),
 (4316, np.float64(0.21213203435596426)),
 (4884, np.float64(0.21213203435596426)),
 (5627, np.float64(0.21213203435596426)),
 (6567, np.float64(0.21213203435596426)),
 (7930, np.float64(0.21213203435596426)),
 (9560, np.float64(0.21213203435596426)),
 (2702, np.float64(0.21081851067789195)),
 (4566, np.float64(0.21081851067789195)),
 (6535, np.float64(0.21081851067789195)),
 (8829, np.float64(0.21081851067789195)),
 (7339, np.float64(0.20942695414584778)),
 (1001, np.float64(0.20795009796401454)),
 (2154, np.float64(0.20795009796401454)),
 (1665, np.float64(0.20701966780270625)),
 (1830, np.float64(0.20701966780270625)),
 (2210, np.float64(0.20701966780270625)),
 (3445, np.float64(0.20701966780270625)),
 (3584, np.float64(0.20701966780270625)),
 (4818, np.float64(0.20701966780270625)),
 (5053, np.float64(0.20701966780270625)),
 (5452, np.float64(0.20701966780270625)),
 (6780, np.float64(0.20701966780270625)),
 (7938, np.float64(0.20701966780270625)),
 (8325, np.float64(0.20701966780270625)),
 (8872, np.float64(0.20701966780270625)),
 (8881, np.float64(0.20701966780270625)),
 (9627, np.float64(0.20701966780270625)),
 (353, np.float64(0.20519567041703082)),
 (5229, np.float64(0.20519567041703082)),
 (6272, np.float64(0.20254787341673333)),
 (6748, np.float64(0.20254787341673333)),
 (8230, np.float64(0.2025478734167333)),
 (2561, np.float64(0.202444082544729)),
 (8050, np.float64(0.202444082544729)),
 (2703, np.float64(0.2022599587389726)),
 (2995, np.float64(0.2022599587389726)),
 (3042, np.float64(0.2022599587389726)),
 (3664, np.float64(0.2022599587389726)),
 (3732, np.float64(0.2022599587389726)),
 (3758, np.float64(0.2022599587389726)),
 (4358, np.float64(0.2022599587389726)),
 (4423, np.float64(0.2022599587389726)),
 (5855, np.float64(0.2022599587389726)),
 (6133, np.float64(0.2022599587389726)),
 (8435, np.float64(0.2022599587389726)),
 (8561, np.float64(0.2022599587389726)),
 (9252, np.float64(0.2022599587389726)),
 (9792, np.float64(0.2022599587389726)),
 (443, np.float64(0.2)),
 (447, np.float64(0.2)),
 (6401, np.float64(0.2)),
 (7272, np.float64(0.2)),
 (371, np.float64(0.1978141420187361)),
 (511, np.float64(0.1978141420187361)),
 (1220, np.float64(0.1978141420187361)),
 (1396, np.float64(0.1978141420187361)),
 (1895, np.float64(0.1978141420187361)),
 (2025, np.float64(0.1978141420187361)),
 (2329, np.float64(0.1978141420187361)),
 (2411, np.float64(0.1978141420187361)),
 (2834, np.float64(0.1978141420187361)),
 (3476, np.float64(0.1978141420187361)),
 (5157, np.float64(0.1978141420187361)),
 (5212, np.float64(0.1978141420187361)),
 (7593, np.float64(0.1978141420187361)),
 (9356, np.float64(0.1978141420187361)),
 (498, np.float64(0.19754591932991794)),
 (618, np.float64(0.19754591932991794)),
 (3324, np.float64(0.19754591932991794)),
 (3959, np.float64(0.19754591932991794)),
 (2527, np.float64(0.19518001458970666)),
 (6629, np.float64(0.19518001458970666)),
 (368, np.float64(0.19364916731037085)),
 (669, np.float64(0.19364916731037085)),
 (821, np.float64(0.19364916731037085)),
 (1333, np.float64(0.19364916731037085)),
 (1627, np.float64(0.19364916731037085)),
 (2197, np.float64(0.19364916731037085)),
 (3012, np.float64(0.19364916731037085)),
 (5125, np.float64(0.19364916731037085)),
 (5403, np.float64(0.19364916731037085)),
 (6878, np.float64(0.19364916731037085)),
 (6936, np.float64(0.19364916731037085)),
 (7776, np.float64(0.19364916731037085)),
 (8255, np.float64(0.19364916731037085)),
 (8839, np.float64(0.19364916731037085)),
 (9598, np.float64(0.19364916731037085)),
 (2109, np.float64(0.19289712886816485)),
 (4215, np.float64(0.19289712886816485)),
 (90, np.float64(0.19069251784911848)),
 (206, np.float64(0.19069251784911848)),
 (435, np.float64(0.19069251784911848)),
 (705, np.float64(0.19069251784911848)),
 (923, np.float64(0.19069251784911848)),
 (1699, np.float64(0.19069251784911848)),
 (1900, np.float64(0.19069251784911848)),
 (2764, np.float64(0.19069251784911848)),
 (2928, np.float64(0.19069251784911848)),
 (2932, np.float64(0.19069251784911848)),
 (3733, np.float64(0.19069251784911848)),
 (3743, np.float64(0.19069251784911848)),
 (3750, np.float64(0.19069251784911848)),
 (3973, np.float64(0.19069251784911848)),
 (4062, np.float64(0.19069251784911848)),
 (5184, np.float64(0.19069251784911848)),
 (7942, np.float64(0.19069251784911848)),
 (8097, np.float64(0.19069251784911848)),
 (8277, np.float64(0.19069251784911848)),
 (8591, np.float64(0.19069251784911848)),
 (9655, np.float64(0.19069251784911848)),
 (677, np.float64(0.18973665961010278)),
 (794, np.float64(0.18973665961010278)),
 (901, np.float64(0.18973665961010278)),
 (2082, np.float64(0.18973665961010278)),
 (3446, np.float64(0.18973665961010278)),
 (4130, np.float64(0.18973665961010278)),
 (5255, np.float64(0.18973665961010278)),
 (5482, np.float64(0.18973665961010278)),
 (5623, np.float64(0.18973665961010278)),
 (6044, np.float64(0.18973665961010278)),
 (6291, np.float64(0.18973665961010278)),
 (6392, np.float64(0.18973665961010278)),
 (6537, np.float64(0.18973665961010278)),
 (8384, np.float64(0.18973665961010278)),
 (5044, np.float64(0.18856180831641267)),
 (8687, np.float64(0.18856180831641267)),
 (155, np.float64(0.18650096164806276)),
 (6756, np.float64(0.18650096164806276)),
 (351, np.float64(0.18605210188381271)),
 (1520, np.float64(0.18605210188381271)),
 (2041, np.float64(0.18605210188381271)),
 (2853, np.float64(0.18605210188381271)),
 (2854, np.float64(0.18605210188381271)),
 (2993, np.float64(0.18605210188381271)),
 (3001, np.float64(0.18605210188381271)),
 (3385, np.float64(0.18605210188381271)),
 (3484, np.float64(0.18605210188381271)),
 (3518, np.float64(0.18605210188381271)),
 (3945, np.float64(0.18605210188381271)),
 (4181, np.float64(0.18605210188381271)),
 (4312, np.float64(0.18605210188381271)),
 (4931, np.float64(0.18605210188381271)),
 (4958, np.float64(0.18605210188381271)),
 (5052, np.float64(0.18605210188381271)),
 (6202, np.float64(0.18605210188381271)),
 (6554, np.float64(0.18605210188381271)),
 (7102, np.float64(0.18605210188381271)),
 (8611, np.float64(0.18605210188381271)),
 (9210, np.float64(0.18605210188381271)),
 (948, np.float64(0.1850583025494013)),
 (2665, np.float64(0.18450624160577703)),
 (3002, np.float64(0.18450624160577703)),
 (7214, np.float64(0.18450624160577703)),
 (8279, np.float64(0.18450624160577703)),
 (8393, np.float64(0.18450624160577703)),
 (9410, np.float64(0.18450624160577703)),
 (4579, np.float64(0.18380365552345193)),
 (1475, np.float64(0.1825741858350554)),
 (1680, np.float64(0.1825741858350554)),
 (1861, np.float64(0.1825741858350554)),
 (2022, np.float64(0.1825741858350554)),
 (2402, np.float64(0.1825741858350554)),
 (2718, np.float64(0.1825741858350554)),
 (3310, np.float64(0.1825741858350554)),
 (3886, np.float64(0.1825741858350554)),
 (5532, np.float64(0.1825741858350554)),
 (5605, np.float64(0.1825741858350554)),
 (5971, np.float64(0.1825741858350554)),
 (6261, np.float64(0.1825741858350554)),
 (6395, np.float64(0.1825741858350554)),
 (6819, np.float64(0.1825741858350554)),
 (8693, np.float64(0.1825741858350554)),
 (8909, np.float64(0.1825741858350554)),
 (8930, np.float64(0.1825741858350554)),
 (376, np.float64(0.18257418583505539)),
 (531, np.float64(0.18257418583505539)),
 (650, np.float64(0.18257418583505539)),
 (935, np.float64(0.18257418583505539)),
 (1032, np.float64(0.18257418583505539)),
 (2419, np.float64(0.18257418583505539)),
 (5364, np.float64(0.18257418583505539)),
 (5655, np.float64(0.18257418583505539)),
 (6713, np.float64(0.18257418583505539)),
 (7493, np.float64(0.18257418583505539)),
 (9256, np.float64(0.18257418583505539)),
 (9450, np.float64(0.18257418583505539)),
 (9834, np.float64(0.18257418583505539)),
 (8272, np.float64(0.18257418583505536)),
 (5248, np.float64(0.18257418583505533)),
 (831, np.float64(0.18070158058105024)),
 (1908, np.float64(0.17928429140015906)),
 (2186, np.float64(0.17928429140015906)),
 (4451, np.float64(0.17928429140015906)),
 (4746, np.float64(0.17928429140015906)),
 (5468, np.float64(0.17928429140015906)),
 (5773, np.float64(0.17928429140015906)),
 (7792, np.float64(0.17928429140015906)),
 (8124, np.float64(0.17928429140015906)),
 (1801, np.float64(0.17902871850985821)),
 (2286, np.float64(0.17888543819998318)),
 (737, np.float64(0.17712297710801905)),
 (2612, np.float64(0.17712297710801905)),
 (521, np.float64(0.17677669529663687)),
 (1286, np.float64(0.17677669529663687)),
 (9133, np.float64(0.17677669529663687)),
 (5463, np.float64(0.17616606585441105)),
 (100, np.float64(0.17616606585441102)),
 (203, np.float64(0.17616606585441102)),
 (585, np.float64(0.17616606585441102)),
 (1201, np.float64(0.17616606585441102)),
 (2976, np.float64(0.17616606585441102)),
 (3448, np.float64(0.17616606585441102)),
 (3521, np.float64(0.17616606585441102)),
 (8251, np.float64(0.17616606585441102)),
 (563, np.float64(0.17568209223157663)),
 (148, np.float64(0.17541160386140586)),
 (265, np.float64(0.17541160386140586)),
 (486, np.float64(0.17541160386140586)),
 (718, np.float64(0.17541160386140586)),
 (796, np.float64(0.17541160386140586)),
 (1272, np.float64(0.17541160386140586)),
 (1647, np.float64(0.17541160386140586)),
 (1677, np.float64(0.17541160386140586)),
 (1768, np.float64(0.17541160386140586)),
 (1884, np.float64(0.17541160386140586)),
 (2412, np.float64(0.17541160386140586)),
 (2489, np.float64(0.17541160386140586)),
 (2578, np.float64(0.17541160386140586)),
 (2894, np.float64(0.17541160386140586)),
 (2965, np.float64(0.17541160386140586)),
 (3076, np.float64(0.17541160386140586)),
 (3082, np.float64(0.17541160386140586)),
 (3263, np.float64(0.17541160386140586)),
 (3524, np.float64(0.17541160386140586)),
 (3531, np.float64(0.17541160386140586)),
 (3700, np.float64(0.17541160386140586)),
 (3990, np.float64(0.17541160386140586)),
 (4100, np.float64(0.17541160386140586)),
 (4493, np.float64(0.17541160386140586)),
 (5039, np.float64(0.17541160386140586)),
 (5209, np.float64(0.17541160386140586)),
 (5632, np.float64(0.17541160386140586)),
 (5935, np.float64(0.17541160386140586)),
 (6579, np.float64(0.17541160386140586)),
 (6656, np.float64(0.17541160386140586)),
 (6660, np.float64(0.17541160386140586)),
 (6990, np.float64(0.17541160386140586)),
 (7003, np.float64(0.17541160386140586)),
 (7899, np.float64(0.17541160386140586)),
 (7923, np.float64(0.17541160386140586)),
 (8150, np.float64(0.17541160386140586)),
 (8544, np.float64(0.17541160386140586)),
 (8572, np.float64(0.17541160386140586)),
 (8610, np.float64(0.17541160386140586)),
 (8739, np.float64(0.17541160386140586)),
 (8999, np.float64(0.17541160386140586)),
 (9263, np.float64(0.17541160386140586)),
 (9822, np.float64(0.17541160386140586)),
 (8398, np.float64(0.17374889710522776)),
 (270, np.float64(0.17320508075688773)),
 (1985, np.float64(0.17320508075688773)),
 (3632, np.float64(0.17320508075688773)),
 (3937, np.float64(0.17320508075688773)),
 (5772, np.float64(0.17320508075688773)),
 (6165, np.float64(0.17320508075688773)),
 (9348, np.float64(0.17320508075688773)),
 (2871, np.float64(0.17213259316477408)),
 (2519, np.float64(0.17056057308448835)),
 (4369, np.float64(0.17056057308448835)),
 (382, np.float64(0.17038855027411945)),
 (997, np.float64(0.17038855027411945)),
 (1259, np.float64(0.17038855027411945)),
 (1635, np.float64(0.17038855027411945)),
 (2424, np.float64(0.17038855027411945)),
 (2843, np.float64(0.17038855027411945)),
 (4018, np.float64(0.17038855027411945)),
 (4397, np.float64(0.17038855027411945)),
 (5185, np.float64(0.17038855027411945)),
 (5298, np.float64(0.17038855027411945)),
 (6570, np.float64(0.17038855027411945)),
 (9109, np.float64(0.17038855027411945)),
 (9900, np.float64(0.17038855027411945)),
 (301, np.float64(0.16903085094570333)),
 (318, np.float64(0.16903085094570333)),
 (495, np.float64(0.16903085094570333)),
 (680, np.float64(0.16903085094570333)),
 (774, np.float64(0.16903085094570333)),
 (787, np.float64(0.16903085094570333)),
 (934, np.float64(0.16903085094570333)),
 (991, np.float64(0.16903085094570333)),
 (1009, np.float64(0.16903085094570333)),
 (1194, np.float64(0.16903085094570333)),
 (1381, np.float64(0.16903085094570333)),
 (1786, np.float64(0.16903085094570333)),
 (2030, np.float64(0.16903085094570333)),
 (2043, np.float64(0.16903085094570333)),
 (2622, np.float64(0.16903085094570333)),
 (2659, np.float64(0.16903085094570333)),
 (3906, np.float64(0.16903085094570333)),
 (3939, np.float64(0.16903085094570333)),
 (4039, np.float64(0.16903085094570333)),
 (4246, np.float64(0.16903085094570333)),
 (4625, np.float64(0.16903085094570333)),
 (4698, np.float64(0.16903085094570333)),
 (5232, np.float64(0.16903085094570333)),
 (5368, np.float64(0.16903085094570333)),
 (5702, np.float64(0.16903085094570333)),
 (6008, np.float64(0.16903085094570333)),
 (6194, np.float64(0.16903085094570333)),
 (6541, np.float64(0.16903085094570333)),
 (7263, np.float64(0.16903085094570333)),
 (7516, np.float64(0.16903085094570333)),
 (7588, np.float64(0.16903085094570333)),
 (7618, np.float64(0.16903085094570333)),
 (8006, np.float64(0.16903085094570333)),
 (8266, np.float64(0.16903085094570333)),
 (8369, np.float64(0.16903085094570333)),
 (8641, np.float64(0.16903085094570333)),
 (8849, np.float64(0.16903085094570333)),
 (8936, np.float64(0.16903085094570333)),
 (9427, np.float64(0.16903085094570333)),
 (403, np.float64(0.16770509831248423)),
 (1868, np.float64(0.16770509831248423)),
 (3861, np.float64(0.16770509831248423)),
 (4570, np.float64(0.16770509831248423)),
 (5165, np.float64(0.16770509831248423)),
 (5374, np.float64(0.16770509831248423)),
 (5863, np.float64(0.16770509831248423)),
 (6966, np.float64(0.16770509831248423)),
 (8944, np.float64(0.16770509831248423)),
 (9126, np.float64(0.16770509831248423)),
 (8403, np.float64(0.16754156331667822)),
 (4116, np.float64(0.16609095970747992)),
 (7784, np.float64(0.16609095970747992)),
 (11, np.float64(0.16514456476895412)),
 (407, np.float64(0.16514456476895412)),
 (2529, np.float64(0.16514456476895412)),
 (2648, np.float64(0.16514456476895412)),
 (2736, np.float64(0.16514456476895412)),
 (2767, np.float64(0.16514456476895412)),
 (3220, np.float64(0.16514456476895412)),
 (3707, np.float64(0.16514456476895412)),
 (3984, np.float64(0.16514456476895412)),
 (4902, np.float64(0.16514456476895412)),
 (5754, np.float64(0.16514456476895412)),
 (7560, np.float64(0.16514456476895412)),
 (7743, np.float64(0.16514456476895412)),
 (8461, np.float64(0.16514456476895412)),

In [133]:
new_data.iloc[distance[3][0]].title

'White Fang'

In [126]:
similarity[1]

array([0.10166571, 0.48291214, 1.        , ..., 0.04454354, 0.04303315,
       0.03901372], shape=(9992,))

In [94]:
new_data.iloc[distance[4][0]]

id                                                   28178
title                                  Hachi: A Dog's Tale
tags     A drama based on the true story of a college p...
Name: 277, dtype: object

In [112]:
def recommend(movies):
    index = new_data[new_data["title"]==movies].index[0]
    distance = sorted(list(enumerate(similarity[index])), reverse=True, key=lambda vector:vector[1])
    for i in distance[0:5]:
        print(new_data.iloc[i[0]].title)

In [113]:
recommend("The Scorpion King 3: Battle for Redemption")

The Scorpion King 3: Battle for Redemption
The Last Kingdom: Seven Kings Must Die
Doctor Strange
Mighty Morphin Power Rangers: The Movie
Descendants