In [1]:
import sqlite3

In [2]:
import pandas as pd

In [3]:
def create_user_movie_matrix(ratings_df):
    """
    Tạo ma trận tiện ích (utility matrix) giữa người dùng và các bộ phim đã được đánh giá.\n
    :params ratings_df: DataFrame chứa dữ liệu đánh giá của người dùng với các cột: 'user_id', 'movie_id', 'rating'.
    :return user_movie_matrix: Ma trận tiện ích với các hàng là người dùng, cột là phim và giá trị là điểm đánh giá.
    Trả về None nếu dữ liệu đầu vào rỗng.
    """
    if ratings_df is None or ratings_df.empty:
        return None
    
    # Tạo ma trận tiện ích giữa người dùng và phim
    user_movie_matrix = ratings_df.pivot_table(
        index='user_id',
        columns='movie_id',
        values='rating'
    ).fillna(0)
    
    return user_movie_matrix

In [20]:
pd.read_sql_query("SELECT user_id, username FROM users", con=conn)

   user_id  username
0        2    Bao Vu
1        1       Duc
2        3      Linh
3        6       QNT
4        7      Test
5        4  Thuy Anh
6        5        Vu

In [21]:
conn = sqlite3.connect("../movies_rating.db")
ratings_df = pd.read_sql_query("SELECT user_id, movie_id, rating FROM ratings", con=conn)

In [22]:
utility_matrix = create_user_movie_matrix(ratings_df)

In [23]:
from sklearn.metrics.pairwise import cosine_similarity

In [24]:
movie_similarity = cosine_similarity(utility_matrix.T)

In [25]:
utility_matrix.T

user_id     1    2    3    4    5    6    7
movie_id
176       0.0  0.0  0.0  0.0  5.0  0.0  0.0
238       0.0  0.0  5.0  0.0  0.0  0.0  0.0
278       4.5  0.0  5.0  0.0  0.0  0.0  0.0
389       0.0  3.5  5.0  0.0  0.0  0.0  0.0
423       3.5  0.0  0.0  0.0  0.0  0.0  0.0
540       0.0  0.0  4.5  0.0  4.5  0.0  0.0
1891      0.0  4.5  0.0  0.0  0.0  0.0  0.0
8587      0.0  0.0  0.0  3.0  0.0  0.0  0.0
14537     0.0  3.0  3.0  0.0  0.0  4.5  0.0
20982     0.0  0.0  0.0  0.0  4.5  0.0  4.5
157336    3.0  0.0  0.0  0.0  0.0  0.0  0.0
176983    5.0  0.0  0.0  0.0  3.0  0.0  0.0
255709    3.5  0.0  0.0  0.0  0.0  0.0  0.0
265712    0.0  0.0  0.0  0.0  3.0  0.0  0.0
372058    0.0  4.5  0.0  4.0  0.0  0.0  0.0
378064    4.5  0.0  0.0  0.0  0.0  0.0  0.0
630566    0.0  5.0  0.0  0.0  0.0  0.0  0.0
667257    0.0  0.0  4.0  0.0  0.0  0.0  0.0
704264    4.0  0.0  0.0  0.0  0.0  0.0  0.0
823219    0.0  3.0  0.0  0.0  0.0  0.0  0.0
1160164   0.0  0.0  0.0  4.0  0.0  0.0  0.0

In [26]:
movie_similarity

array([[1.        , 0.        , 0.        , 0.        , 0.        ,
        0.70710678, 0.        , 0.        , 0.        , 0.70710678,
        0.        , 0.51449576, 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.74329415, 0.81923192, 0.        ,
        0.70710678, 0.        , 0.        , 0.48507125, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 1.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.74329415, 1.        , 0.60893029, 0.66896473,
        0.52558833, 0.        , 0.        , 0.36055062, 0.        ,
        0.66896473, 0.57363252, 0.66896473, 0.        , 0.        ,
        0.66896473, 0.        , 0.74329415, 0.66896473, 0.        ,
        0.        ],
       [0.        , 0.81923192, 0.60893029, 1.        , 0.        ,
        0.57928445, 0.57346234, 0.        , 0.67555595, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.4286111 ,
        0.        , 0.57346234, 0.81923192, 0.        , 0.57346234,
        0.        ],
       [0.        , 0.        , 0.66896473, 0.        , 1.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        , 0.85749293, 1.        , 0.        , 0.        ,
        1.        , 0.        , 0.        , 1.        , 0.        ,
        0.        ],
       [0.70710678, 0.70710678, 0.52558833, 0.57928445, 0.        ,
        1.        , 0.        , 0.        , 0.34299717, 0.5       ,
        0.        , 0.36380344, 0.        , 0.70710678, 0.        ,
        0.        , 0.        , 0.70710678, 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.57346234, 0.        ,
        0.        , 1.        , 0.        , 0.48507125, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.74740932,
        0.        , 1.        , 0.        , 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 1.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.66436384,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        ],
       [0.        , 0.48507125, 0.36055062, 0.67555595, 0.        ,
        0.34299717, 0.48507125, 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.36254677,
        0.        , 0.48507125, 0.48507125, 0.        , 0.48507125,
        0.        ],
       [0.70710678, 0.        , 0.        , 0.        , 0.        ,
        0.5       , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.36380344, 0.        , 0.70710678, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.66896473, 0.        , 1.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        , 0.85749293, 1.        , 0.        , 0.        ,
        1.        , 0.        , 0.        , 1.        , 0.        ,
        0.        ],
       [0.51449576, 0.        , 0.57363252, 0.        , 0.85749293,
        0.36380344, 0.        , 0.        , 0.        , 0.36380344,
        0.85749293, 1.        , 0.85749293, 0.51449576, 0.        ,
        0.85749293, 0.        , 0.        , 0.85749293, 0.        ,
        0.        ],
       [0.        , 0.        , 0.66896473, 0.        , 1.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        , 0.85749293, 1.        , 0.        , 0.        ,
        1.        , 0.        , 0.        , 1.        , 0.        ,
        0.        ],
       [1.        , 0.        , 0.        , 0.        , 0.        ,
        0.70710678, 0.        , 0.        , 0.        , 0.70710678,
        0.        , 0.51449576, 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.4286111 , 0.        ,
        0.        , 0.74740932, 0.66436384, 0.36254677, 0.        ,
        0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.74740932, 0.        , 0.        , 0.74740932,
        0.66436384],
       [0.        , 0.        , 0.66896473, 0.        , 1.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        , 0.85749293, 1.        , 0.        , 0.        ,
        1.        , 0.        , 0.        , 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.57346234, 0.        ,
        0.        , 1.        , 0.        , 0.48507125, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.74740932,
        0.        , 1.        , 0.        , 0.        , 1.        ,
        0.        ],
       [0.        , 1.        , 0.74329415, 0.81923192, 0.        ,
        0.70710678, 0.        , 0.        , 0.48507125, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 1.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.66896473, 0.        , 1.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        , 0.85749293, 1.        , 0.        , 0.        ,
        1.        , 0.        , 0.        , 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.57346234, 0.        ,
        0.        , 1.        , 0.        , 0.48507125, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.74740932,
        0.        , 1.        , 0.        , 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 1.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.66436384,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        ]])

In [29]:
utility_matrix

movie_id,176,238,278,389,423,540,1891,8587,14537,20982,...,176983,255709,265712,372058,378064,630566,667257,704264,823219,1160164
user_id,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,4.5,0.0,3.5,0.0,0.0,0.0,0.0,0.0,...,5.0,3.5,0.0,0.0,4.5,0.0,0.0,4.0,0.0,0.0
2,0.0,0.0,0.0,3.5,0.0,0.0,4.5,0.0,3.0,0.0,...,0.0,0.0,0.0,4.5,0.0,5.0,0.0,0.0,3.0,0.0
3,0.0,5.0,5.0,5.0,0.0,4.5,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,...,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,4.0
5,5.0,0.0,0.0,0.0,0.0,4.5,0.0,0.0,0.0,4.5,...,3.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.5,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [31]:
user_idx = utility_matrix.index.get_loc(3)

In [32]:
user_idx

2

In [33]:
user_similarity = cosine_similarity(utility_matrix)

In [51]:
similar_scores = user_similarity[1]

In [52]:
similar_scores

array([0.        , 1.        , 0.24696416, 0.28728383, 0.        ,
       0.30658568, 0.        ])

In [53]:
similar_users = list(enumerate(similar_scores))

In [54]:
similar_users

[(0, np.float64(0.0)),
 (1, np.float64(1.0000000000000002)),
 (2, np.float64(0.24696416458508677)),
 (3, np.float64(0.2872838322195115)),
 (4, np.float64(0.0)),
 (5, np.float64(0.3065856781845576)),
 (6, np.float64(0.0))]

In [55]:
similar_users = sorted(similar_users, key=lambda x: x[1], reverse=True)

In [56]:
similar_users

[(1, np.float64(1.0000000000000002)),
 (5, np.float64(0.3065856781845576)),
 (3, np.float64(0.2872838322195115)),
 (2, np.float64(0.24696416458508677)),
 (0, np.float64(0.0)),
 (4, np.float64(0.0)),
 (6, np.float64(0.0))]

In [57]:
user_ratings = utility_matrix.iloc[user_idx]

In [58]:
user_ratings

movie_id
176        0.0
238        5.0
278        5.0
389        5.0
423        0.0
540        4.5
1891       0.0
8587       0.0
14537      3.0
20982      0.0
157336     0.0
176983     0.0
255709     0.0
265712     0.0
372058     0.0
378064     0.0
630566     0.0
667257     4.0
704264     0.0
823219     0.0
1160164    0.0
Name: 3, dtype: float64

In [59]:
unwatched_movies = user_ratings[user_ratings == 0].index

In [60]:
unwatched_movies

Index([    176,     423,    1891,    8587,   20982,  157336,  176983,  255709,
        265712,  372058,  378064,  630566,  704264,  823219, 1160164],
      dtype='int64', name='movie_id')

In [61]:
similar_users

[(1, np.float64(1.0000000000000002)),
 (5, np.float64(0.3065856781845576)),
 (3, np.float64(0.2872838322195115)),
 (2, np.float64(0.24696416458508677)),
 (0, np.float64(0.0)),
 (4, np.float64(0.0)),
 (6, np.float64(0.0))]

In [66]:
utility_matrix[389]

user_id
1    0.0
2    3.5
3    5.0
4    0.0
5    0.0
6    0.0
7    0.0
Name: 389, dtype: float64

In [67]:
(0.3065856781845576 * 3.5 + 0.2872838322195115 * 5.0)/(0.3065856781845576 + 0.2872838322195115)

4.225623627379128